---
- name: Set Fedora related facts
  set_fact:
    is_fedora: true
  when: (ansible_distribution == 'Fedora')

- name: Set CentOS related facts
  set_fact:
    is_centos: true
  when: (ansible_distribution == 'CentOS')

# The /.dockerenv file can be found in Docker images and containers 
- name: Check for Docker related file
  stat:
    path: /.dockerenv
  register: docker_result
  ignore_errors: true
  
- name: Set Docker fact to true
  set_fact:
    is_docker: true
  when: docker_result.stat.exists

# If a /home/vagrant directory exists then we assume a Vagrant box is being used
- name: Check for Vagrant related directory
  stat:
    path: "{{ vagrant_home_dir }}"
  register: vagrant_result
  ignore_errors: true
  
- name: Set Vagrant fact to true
  set_fact:
    is_vagrant: true
  when: vagrant_result.stat.exists
